continuum_section_1:
  ros__parameters:
    num_sec: 1
    num_joints: 2
    num_cables: 12
    num_sec_cables: 12
    num_joints_urdf: 4
    a: [0.04, 0.035, 0.03]
    b: 0.015
    alpha: [0.0, 0.5235987755982988, 1.308996938995747]
    preload: 0.0
