<?xml version="1.0"?>

<robot name="continuum_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="Section1" params="name">

    <xacro:property name="vert_len" value="0.0035000000000000005" />
    <xacro:property name="vert_rad" value="0.035" />
    <xacro:property name="link_len" value="0.03" />
    <xacro:property name="cyl_radius" value="0.0035000000000000005" />
    <xacro:property name="link_mass" value="0.09005375341515143" />
    <xacro:property name="link_Ixx" value="7.029821125970258e-06" />
    <xacro:property name="link_Iyy" value="7.029821125970258e-06" />
    <xacro:property name="link_Izz" value="5.515792396678026e-07" />
    <xacro:property name="disk_mass" value="1.050627123176767" />
    <xacro:property name="disk_Ixx" value="0.00032282707166112786" />
    <xacro:property name="disk_Iyy" value="0.00032282707166112786" />
    <xacro:property name="disk_Izz" value="0.0006435091129457698" />

        <link name="S1B">

    	    <visual>
    		    <origin rpy="0 0 0" xyz="0 0 0 "/>
    		    <geometry>
    			    <cylinder length="${vert_len}" radius="${vert_rad}"/>
    		    </geometry>
    	    	<material name="Transparent">
    		    	<color rgba="0.5 0.5 0.5 0.5"/>
    	    	</material>
        	</visual>

        </link>

        <joint name="S1JT_in" type="continuous">
    	    <parent link="S1B"/>
    	    <child link="S1L0" />
    	    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <axis xyz="0 0 1"/>
        </joint>


        <link name="S1L0">
    	    <visual>
    		    <origin rpy="0 0 0" xyz="0 0 0.0075"/>
    		    <geometry>
    			    <cylinder length="0.015" radius="${cyl_radius}"/>
    		    </geometry>
    		    <material name="Black">
    		    	<color rgba="1 1 1 1"/>
    	    	</material>
        	</visual>
        </link>

        <joint name="S1D0J" type="fixed">
    	    <axis xyz="0 0 1"/>
    	    <parent link="S1L0"/>
    	    <child link="S1D0" />
        	<origin rpy="0 0 0" xyz="0 0 0"/>
        </joint>

        <link name="S1D0">
    	    <visual>
    		    <origin rpy="0 0 0" xyz="0 0 0"/>
    		    <geometry>
    			    <cylinder length="${vert_len}" radius="${vert_rad}"/>
    		    </geometry>
    		    <material name="Red">
    		    	<color rgba="1 0 0 1"/>
    	    	</material>
        	</visual>
        </link>


        <joint name="S1J0" type="revolute">
    	    <parent link="S1L0"/>
    	    <child link="S1L1"/>
    	    <origin rpy="0 0 0" xyz="0 0 0.015"/>
            <limit lower="-0.5235987755982988" upper="0.5235987755982988" velocity="100.0" effort="100.0"/>
    	    <axis xyz="0 1 0"/>
        </joint>




        <link name="S1L1">
    	    <visual>
    		    <origin rpy="0 0 0" xyz="0 0 0.015"/>
    		    <geometry>
    			    <cylinder length="0.03" radius="${cyl_radius}"/>
    		    </geometry>
    		    <material name="Black">
    		    	<color rgba="1 1 1 1"/>
    	    	</material>
        	</visual>
        </link>


        <joint name="S1D1J" type="fixed">
    	    <axis xyz="0 0 1"/>
    	    <parent link="S1L1"/>
    	    <child link="S1D1" />
        	<origin rpy="0 0 0" xyz="0 0 0.015"/>
        </joint>

        <link name="S1D1">
    	    <visual>
    		    <origin rpy="0 0 0" xyz="0 0 0"/>
    		    <geometry>
    			    <cylinder length="${vert_len}" radius="${vert_rad}"/>
    		    </geometry>
    		    <material name="Red">
    		    	<color rgba="1 0 0 1"/>
    	    	</material>
        	</visual>
        </link>


        <joint name="S1J1" type="revolute">
    	    <parent link="S1L1"/>
    	    <child link="S1L2"/>
    	    <origin rpy="0 0 0" xyz="0 0 0.03"/>
            <limit lower="-0.5235987755982988" upper="0.5235987755982988" velocity="100.0" effort="100.0"/>
    	    <mimic joint="S1J0" />
    	    <axis xyz="0 1 0"/>
        </joint>




        <link name="S1L2">
    	    <visual>
    		    <origin rpy="0 0 0" xyz="0 0 0.015"/>
    		    <geometry>
    			    <cylinder length="0.03" radius="${cyl_radius}"/>
    		    </geometry>
    		    <material name="Black">
    		    	<color rgba="1 1 1 1"/>
    	    	</material>
        	</visual>
        </link>


        <joint name="S1D2J" type="fixed">
    	    <axis xyz="0 0 1"/>
    	    <parent link="S1L2"/>
    	    <child link="S1D2" />
        	<origin rpy="0 0 0" xyz="0 0 0.015"/>
        </joint>

        <link name="S1D2">
    	    <visual>
    		    <origin rpy="0 0 0" xyz="0 0 0"/>
    		    <geometry>
    			    <cylinder length="${vert_len}" radius="${vert_rad}"/>
    		    </geometry>
    		    <material name="Red">
    		    	<color rgba="1 0 0 1"/>
    	    	</material>
        	</visual>
        </link>


        <joint name="S1J2" type="revolute">
    	    <parent link="S1L2"/>
    	    <child link="S1L3"/>
    	    <origin rpy="0 0 0" xyz="0 0 0.03"/>
            <limit lower="-0.5235987755982988" upper="0.5235987755982988" velocity="100.0" effort="100.0"/>
    	    <mimic joint="S1J1" />
    	    <axis xyz="0 1 0"/>
        </joint>




        <link name="S1L3">
    	    <visual>
    		    <origin rpy="0 0 0" xyz="0 0 0.015"/>
    		    <geometry>
    			    <cylinder length="0.03" radius="${cyl_radius}"/>
    		    </geometry>
    		    <material name="Black">
    		    	<color rgba="1 1 1 1"/>
    	    	</material>
        	</visual>
        </link>


        <joint name="S1D3J" type="fixed">
    	    <axis xyz="0 0 1"/>
    	    <parent link="S1L3"/>
    	    <child link="S1D3" />
        	<origin rpy="0 0 0" xyz="0 0 0.015"/>
        </joint>

        <link name="S1D3">
    	    <visual>
    		    <origin rpy="0 0 0" xyz="0 0 0"/>
    		    <geometry>
    			    <cylinder length="${vert_len}" radius="${vert_rad}"/>
    		    </geometry>
    		    <material name="Red">
    		    	<color rgba="1 0 0 1"/>
    	    	</material>
        	</visual>
        </link>


        <joint name="S1J3" type="revolute">
    	    <parent link="S1L3"/>
    	    <child link="S1L4"/>
    	    <origin rpy="0 0 0" xyz="0 0 0.03"/>
            <limit lower="-0.5235987755982988" upper="0.5235987755982988" velocity="100.0" effort="100.0"/>
    	    <mimic joint="S1J2" />
    	    <axis xyz="0 1 0"/>
        </joint>




        <link name="S1L4">
    	    <visual>
    		    <origin rpy="0 0 0" xyz="0 0 0.0075"/>
    		    <geometry>
    			    <cylinder length="0.015" radius="${cyl_radius}"/>
    		    </geometry>
    		    <material name="Black">
    		    	<color rgba="1 1 1 1"/>
    	    	</material>
        	</visual>
        </link>


        <joint name="S1JT_out" type="continuous">
    	    <parent link="S1L4"/>
    	    <child link="S1E" />
    	    <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 ${link_len/2}" />
    	    <axis xyz="0 0 1"/>
    	    <mimic joint="S1JT_in" multiplier="-1" />
        </joint>


        <link name="S1E">

    	    <visual>
    		    <origin rpy="0 0 0" xyz="0 0 0"/>
    		    <geometry>
    			    <cylinder length="${vert_len}" radius="${vert_rad}"/>
    		    </geometry>
    		    <material name="Red">
    		    	<color rgba="1 0 0 1"/>
    	    	</material>
        	</visual>
        </link>


    </xacro:macro>

</robot>
